name: Compile and release

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: write
    if: "!contains(github.event.head_commit.message, '[ci]')"

    steps:
      - uses: actions/checkout@v3

      - name: Set environment variables
        run: echo SCRIPTS_PATH=$(pwd) >> $GITHUB_ENV

      - name: Setup SourcePawn Compiler ${{ matrix.SM_VERSION }}
        id: setup_sp
        uses: rumblefrog/setup-sp@master
        with:
          version: "1.11.x"
          version-file: ./scripting/TF2-ProperClassWeaponAnimations.sp

      - name: Download SourcePawn plugin dependencies
        uses: Zabaniya001/SPDependy@v1
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Parse toml
        uses: SebRollen/toml-action@v1.0.1
        id: read_toml
        with:
          file: 'sp.toml'
          field: 'Compile.plugins'

      - name: Compile plugins
        run: |
          mkdir plugins
          my_array=$(echo ${{ toJSON(steps.read_toml.outputs.value) }} | jq -r '.[]')
          for plugin in $my_array; do
            spcomp -w234 -O2 -v2 -i"scripting/include" -i".temp/include" -o"plugins/${plugin}.smx" "scripting/${plugin}.sp"
          done
        working-directory: ${{ env.SCRIPTS_PATH }}

      - name: Changelog
        id: changelog
        uses: mindsers/changelog-reader-action@v2

      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Zip output
        run: |
          zip -qq -y -r ${{ github.event.repository.name }}-${{ steps.setup_sp.outputs.plugin-version }}.zip configs plugins scripting extensions gamedata translations data
        working-directory: ${{ env.SCRIPTS_PATH }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ steps.setup_sp.outputs.plugin-version }}
          artifacts: "${{ github.event.repository.name }}-${{ steps.setup_sp.outputs.plugin-version }}.zip"
          body: ${{ steps.changelog.outputs.changes }}
          draft: false
          allowUpdates: true
          prerelease: false
          replacesArtifacts: true